[main]
font=JetBrains Mono NF:size=15
terminal=alacritty -e
prompt="  "
layer=overlay
lines=10
width=45
dpi-aware=no
inner-pad=20
horizontal-pad=30
vertical-pad=30
match-counter=no
# Centré sur l'écran
anchor=center
fields=name,generic,comment,categories,filename,keywords

[colors]
# Gris très foncé translucide
background=1a1a1ae6
text=e0e0e0ff
prompt=a8a8a8ff
placeholder=666666ff
input=ffffffff
# Couleur d'accentuation (cyan/menthe)
match=8bd5caff
# Fond de la sélection
selection=333333ff
selection-text=ffffffff
selection-match=8bd5caff
border=333333ff

[border]
radius=25
width=2

[dmenu]
mode=text
exit-immediately-if-empty=yes
