[main]
font=JetBrains Mono NF:size=17
terminal=alacritty -e
prompt=" "
layer=overlay
lines=10
width=40
dpi-aware=no
inner-pad=15
horizontal-pad=30
vertical-pad=20
match-counter=no
anchor=bottom
# Décalage du bas pour ne pas toucher le bord
y-margin=50
# Force le focus
fields=name,generic,comment,categories,filename,keywords

[colors]
# Noir profond avec légère transparence
background=000000f0
text=ffffffdd
prompt=ffffffaa
placeholder=666666ff
input=ffffffff
match=ff0000ff
selection=333333ff
selection-text=ffffffff
selection-match=ff0000ff
border=333333ff

[border]
radius=20
width=1

[dmenu]
mode=text
exit-immediately-if-empty=yes
