general {
    no_fade_in = true
    no_fade_out = true
    # Permet de déverrouiller immédiatement si PAM (fprintd) dit OK
    ignore_empty_input = true
}

background {
    monitor =
    path = ~/Images/wallpaper.jpg
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 2
    blur_size = 6
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    outer_color = rgba(255, 255, 255, 0)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    rounding = -1
    check_color = rgb(204, 136, 34)
    fail_color = rgb(204, 34, 34)
    # C'est ici que la magie opère pour l'empreinte
    placeholder_text = <i><span foreground="##cdd6f4">Empreinte ou mot de passe...</span></i>
    hide_input = false
    position = 0, -100
    halign = center
    valign = center
}

# Heure (Style Apple)
label {
    monitor =
    text = $TIME
    color = rgba(255, 255, 255, 0.8)
    font_size = 120
    font_family = JetBrains Mono NF Bold
    position = 0, 300
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%A, %d %B')"
    color = rgba(255, 255, 255, 0.8)
    font_size = 24
    font_family = JetBrains Mono NF
    position = 0, 180
    halign = center
    valign = center
}

# Message utilisateur
label {
    monitor =
    text = Bonjour, $USER
    color = rgba(255, 255, 255, 0.8)
    font_size = 18
    font_family = JetBrains Mono NF
    position = 0, -30
    halign = center
    valign = center
}
